language: c

sudo: true

dist: focal

services: docker
install:
- docker pull devkitpro/devkita64:latest
script:
- docker run -e ENABLE_COMPATIBILITY_REPORTING -v $TRAVIS_BUILD_DIR:/Switch-incognito
  devkitpro/devkita64 /bin/bash -ex /Switch-incognito/.travis/.build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
