name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
    - name: Checkout master branch
      run: git clone --recursive https://github.com/tiansongyu/incognito_ch.git $GITHUB_WORKSPACE

    - name: make all
      run: |
        cd $GITHUB_WORKSPACE
        make
    - uses: actions/upload-artifact@master
      with:
        name: Build
        path: $GITHUB_WORKSPACE/out/incognito_zh.nro
