name: CI
on:
  push:
    branches: [ test]
jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
    - name: Checkout master branch
      run: git clone --recursive https://github.com/tiansongyu/Switch-incognito.git $GITHUB_WORKSPACE

    - name: make all
      run: |
        cd $GITHUB_WORKSPACE
        make -j$(nproc) > extra-file.txt
    - uses: actions/upload-artifact@master
      with:
        name: Build
        path: out/Switch-incognito.nro
    - uses: actions/upload-artifact@master
      with:
        name: result
        path: extra-file.txt
